create extension if not exists "uuid-ossp";

create table if not exists "country"
(
    id   UUID unique        not null default uuid_generate_v4() primary key,
    name varchar(50) unique not null,
    code varchar(5) unique not null
);

alter table "country"
    owner to postgres;

-- Insert country data
INSERT INTO country (name, code) VALUES ('Fiji', 'FJ');
INSERT INTO country (name, code) VALUES ('Tanzania', 'TZ');
INSERT INTO country (name, code) VALUES ('Western Sahara', 'EH');
INSERT INTO country (name, code) VALUES ('Canada', 'CA');
INSERT INTO country (name, code) VALUES ('United States', 'US');
INSERT INTO country (name, code) VALUES ('Kazakhstan', 'KZ');
INSERT INTO country (name, code) VALUES ('Uzbekistan', 'UZ');
INSERT INTO country (name, code) VALUES ('Papua New Guinea', 'PG');
INSERT INTO country (name, code) VALUES ('Indonesia', 'ID');
INSERT INTO country (name, code) VALUES ('Argentina', 'AR');
INSERT INTO country (name, code) VALUES ('Chile', 'CL');
INSERT INTO country (name, code) VALUES ('Democratic Republic of the Congo', 'CD');
INSERT INTO country (name, code) VALUES ('Somalia', 'SO');
INSERT INTO country (name, code) VALUES ('Kenya', 'KE');
INSERT INTO country (name, code) VALUES ('Sudan', 'SD');
INSERT INTO country (name, code) VALUES ('Chad', 'TD');
INSERT INTO country (name, code) VALUES ('Haiti', 'HT');
INSERT INTO country (name, code) VALUES ('Dominican Republic', 'DO');
INSERT INTO country (name, code) VALUES ('Russia', 'RU');
INSERT INTO country (name, code) VALUES ('Bahamas', 'BS');
INSERT INTO country (name, code) VALUES ('Falkland Islands', 'FK');
INSERT INTO country (name, code) VALUES ('Norway', 'NO');
INSERT INTO country (name, code) VALUES ('Greenland', 'GL');
INSERT INTO country (name, code) VALUES ('Timor-Leste', 'TL');
INSERT INTO country (name, code) VALUES ('South Africa', 'ZA');
INSERT INTO country (name, code) VALUES ('Lesotho', 'LS');
INSERT INTO country (name, code) VALUES ('Mexico', 'MX');
INSERT INTO country (name, code) VALUES ('Uruguay', 'UY');
INSERT INTO country (name, code) VALUES ('Brazil', 'BR');
INSERT INTO country (name, code) VALUES ('Bolivia', 'BO');
INSERT INTO country (name, code) VALUES ('Peru', 'PE');
INSERT INTO country (name, code) VALUES ('Colombia', 'CO');
INSERT INTO country (name, code) VALUES ('Panama', 'PA');
INSERT INTO country (name, code) VALUES ('Costa Rica', 'CR');
INSERT INTO country (name, code) VALUES ('Nicaragua', 'NI');
INSERT INTO country (name, code) VALUES ('Honduras', 'HN');
INSERT INTO country (name, code) VALUES ('El Salvador', 'SV');
INSERT INTO country (name, code) VALUES ('Guatemala', 'GT');
INSERT INTO country (name, code) VALUES ('Belize', 'BZ');
INSERT INTO country (name, code) VALUES ('Venezuela', 'VE');
INSERT INTO country (name, code) VALUES ('Guyana', 'GY');
INSERT INTO country (name, code) VALUES ('Suriname', 'SR');
INSERT INTO country (name, code) VALUES ('France', 'FR');
INSERT INTO country (name, code) VALUES ('Ecuador', 'EC');
INSERT INTO country (name, code) VALUES ('Puerto Rico', 'PR');
INSERT INTO country (name, code) VALUES ('Jamaica', 'JM');
INSERT INTO country (name, code) VALUES ('Cuba', 'CU');
INSERT INTO country (name, code) VALUES ('Zimbabwe', 'ZW');
INSERT INTO country (name, code) VALUES ('Botswana', 'BW');
INSERT INTO country (name, code) VALUES ('Namibia', 'NA');
INSERT INTO country (name, code) VALUES ('Senegal', 'SN');
INSERT INTO country (name, code) VALUES ('Mali', 'ML');
INSERT INTO country (name, code) VALUES ('Mauritania', 'MR');
INSERT INTO country (name, code) VALUES ('Benin', 'BJ');
INSERT INTO country (name, code) VALUES ('Niger', 'NE');
INSERT INTO country (name, code) VALUES ('Nigeria', 'NG');
INSERT INTO country (name, code) VALUES ('Cameroon', 'CM');
INSERT INTO country (name, code) VALUES ('Togo', 'TG');
INSERT INTO country (name, code) VALUES ('Ghana', 'GH');
INSERT INTO country (name, code) VALUES ('Côted''Ivoire', 'CI');
INSERT INTO country (name, code) VALUES ('Guinea', 'GN');
INSERT INTO country (name, code) VALUES ('Guinea-Bissau', 'GW');
INSERT INTO country (name, code) VALUES ('Liberia', 'LR');
INSERT INTO country (name, code) VALUES ('Sierra Leone', 'SL');
INSERT INTO country (name, code) VALUES ('Burkina Faso', 'BF');
INSERT INTO country (name, code) VALUES ('Central African Republic', 'CF');
INSERT INTO country (name, code) VALUES ('Republic of the Congo', 'CG');
INSERT INTO country (name, code) VALUES ('Gabon', 'GA');
INSERT INTO country (name, code) VALUES ('Equatorial Guinea', 'GQ');
INSERT INTO country (name, code) VALUES ('Zambia', 'ZM');
INSERT INTO country (name, code) VALUES ('Malawi', 'MW');
INSERT INTO country (name, code) VALUES ('Mozambique', 'MZ');
INSERT INTO country (name, code) VALUES ('Eswatini', 'SZ');
INSERT INTO country (name, code) VALUES ('Angola', 'AO');
INSERT INTO country (name, code) VALUES ('Burundi', 'BI');
INSERT INTO country (name, code) VALUES ('Israel', 'IL');
INSERT INTO country (name, code) VALUES ('Lebanon', 'LB');
INSERT INTO country (name, code) VALUES ('Madagascar', 'MG');
INSERT INTO country (name, code) VALUES ('Palestine', 'PS');
INSERT INTO country (name, code) VALUES ('The Gambia', 'GM');
INSERT INTO country (name, code) VALUES ('Tunisia', 'TN');
INSERT INTO country (name, code) VALUES ('Algeria', 'DZ');
INSERT INTO country (name, code) VALUES ('Jordan', 'JO');
INSERT INTO country (name, code) VALUES ('United Arab Emirates', 'AE');
INSERT INTO country (name, code) VALUES ('Qatar', 'QA');
INSERT INTO country (name, code) VALUES ('Kuwait', 'KW');
INSERT INTO country (name, code) VALUES ('Iraq', 'IQ');
INSERT INTO country (name, code) VALUES ('Oman', 'OM');
INSERT INTO country (name, code) VALUES ('Vanuatu', 'VU');
INSERT INTO country (name, code) VALUES ('Cambodia', 'KH');
INSERT INTO country (name, code) VALUES ('Thailand', 'TH');
INSERT INTO country (name, code) VALUES ('Lao PDR', 'LA');
INSERT INTO country (name, code) VALUES ('Myanmar', 'MM');
INSERT INTO country (name, code) VALUES ('Vietnam', 'VN');
INSERT INTO country (name, code) VALUES ('Dem. Rep. Korea', 'KP');
INSERT INTO country (name, code) VALUES ('Republic of Korea', 'KR');
INSERT INTO country (name, code) VALUES ('Mongolia', 'MN');
INSERT INTO country (name, code) VALUES ('India', 'IN');
INSERT INTO country (name, code) VALUES ('Bangladesh', 'BD');
INSERT INTO country (name, code) VALUES ('Bhutan', 'BT');
INSERT INTO country (name, code) VALUES ('Nepal', 'NP');
INSERT INTO country (name, code) VALUES ('Pakistan', 'PK');
INSERT INTO country (name, code) VALUES ('Afghanistan', 'AF');
INSERT INTO country (name, code) VALUES ('Tajikistan', 'TJ');
INSERT INTO country (name, code) VALUES ('Kyrgyzstan', 'KG');
INSERT INTO country (name, code) VALUES ('Turkmenistan', 'TM');
INSERT INTO country (name, code) VALUES ('Iran', 'IR');
INSERT INTO country (name, code) VALUES ('Syria', 'SY');
INSERT INTO country (name, code) VALUES ('Armenia', 'AM');
INSERT INTO country (name, code) VALUES ('Sweden', 'SE');
INSERT INTO country (name, code) VALUES ('Belarus', 'BY');
INSERT INTO country (name, code) VALUES ('Ukraine', 'UA');
INSERT INTO country (name, code) VALUES ('Poland', 'PL');
INSERT INTO country (name, code) VALUES ('Austria', 'AT');
INSERT INTO country (name, code) VALUES ('Hungary', 'HU');
INSERT INTO country (name, code) VALUES ('Moldova', 'MD');
INSERT INTO country (name, code) VALUES ('Romania', 'RO');
INSERT INTO country (name, code) VALUES ('Lithuania', 'LT');
INSERT INTO country (name, code) VALUES ('Latvia', 'LV');
INSERT INTO country (name, code) VALUES ('Estonia', 'EE');
INSERT INTO country (name, code) VALUES ('Germany', 'DE');
INSERT INTO country (name, code) VALUES ('Bulgaria', 'BG');
INSERT INTO country (name, code) VALUES ('Greece', 'GR');
INSERT INTO country (name, code) VALUES ('Turkey', 'TR');
INSERT INTO country (name, code) VALUES ('Albania', 'AL');
INSERT INTO country (name, code) VALUES ('Croatia', 'HR');
INSERT INTO country (name, code) VALUES ('Switzerland', 'CH');
INSERT INTO country (name, code) VALUES ('Luxembourg', 'LU');
INSERT INTO country (name, code) VALUES ('Belgium', 'BE');
INSERT INTO country (name, code) VALUES ('Netherlands', 'NL');
INSERT INTO country (name, code) VALUES ('Portugal', 'PT');
INSERT INTO country (name, code) VALUES ('Spain', 'ES');
INSERT INTO country (name, code) VALUES ('Ireland', 'IE');
INSERT INTO country (name, code) VALUES ('New Caledonia', 'NC');
INSERT INTO country (name, code) VALUES ('Solomon Islands', 'SB');
INSERT INTO country (name, code) VALUES ('New Zealand', 'NZ');
INSERT INTO country (name, code) VALUES ('Australia', 'AU');
INSERT INTO country (name, code) VALUES ('Sri Lanka', 'LK');
INSERT INTO country (name, code) VALUES ('China', 'CN');
INSERT INTO country (name, code) VALUES ('Taiwan', 'TW');
INSERT INTO country (name, code) VALUES ('Italy', 'IT');
INSERT INTO country (name, code) VALUES ('Denmark', 'DK');
INSERT INTO country (name, code) VALUES ('United Kingdom', 'GB');
INSERT INTO country (name, code) VALUES ('Iceland', 'IS');
INSERT INTO country (name, code) VALUES ('Azerbaijan', 'AZ');
INSERT INTO country (name, code) VALUES ('Georgia', 'GE');
INSERT INTO country (name, code) VALUES ('Philippines', 'PH');
INSERT INTO country (name, code) VALUES ('Malaysia', 'MY');
INSERT INTO country (name, code) VALUES ('Brunei Darussalam', 'BN');
INSERT INTO country (name, code) VALUES ('Slovenia', 'SI');
INSERT INTO country (name, code) VALUES ('Finland', 'FI');
INSERT INTO country (name, code) VALUES ('Slovakia', 'SK');
INSERT INTO country (name, code) VALUES ('Czech Republic', 'CZ');
INSERT INTO country (name, code) VALUES ('Eritrea', 'ER');
INSERT INTO country (name, code) VALUES ('Japan', 'JP');
INSERT INTO country (name, code) VALUES ('Paraguay', 'PY');
INSERT INTO country (name, code) VALUES ('Yemen', 'YE');
INSERT INTO country (name, code) VALUES ('Saudi Arabia', 'SA');
INSERT INTO country (name, code) VALUES ('Northern Cyprus', 'CYP');
INSERT INTO country (name, code) VALUES ('Cyprus', 'CY');
INSERT INTO country (name, code) VALUES ('Morocco', 'MA');
INSERT INTO country (name, code) VALUES ('Egypt', 'EG');
INSERT INTO country (name, code) VALUES ('Libya', 'LY');
INSERT INTO country (name, code) VALUES ('Ethiopia', 'ET');
INSERT INTO country (name, code) VALUES ('Djibouti', 'DJ');
INSERT INTO country (name, code) VALUES ('Somaliland', 'SOM');
INSERT INTO country (name, code) VALUES ('Uganda', 'UG');
INSERT INTO country (name, code) VALUES ('Rwanda', 'RW');
INSERT INTO country (name, code) VALUES ('Bosnia and Herzegovina', 'BA');
INSERT INTO country (name, code) VALUES ('Macedonia', 'MK');
INSERT INTO country (name, code) VALUES ('Serbia', 'RS');
INSERT INTO country (name, code) VALUES ('Montenegro', 'ME');
INSERT INTO country (name, code) VALUES ('Kosovo', 'XK');
INSERT INTO country (name, code) VALUES ('Trinidad and Tobago', 'TT');
INSERT INTO country (name, code) VALUES ('South Sudan', 'SS');
